// ovid4j — Java port of OVID (https://github.com/clawdreyhepburn/ovid), Apache-2.0.
package io.github.mfanti.ovid4j;

import java.security.KeyPair;
import java.util.List;

/**
 * Options for {@link Ovid#createOvid}. Use the builder; only {@code issuerKeys}
 * and at least one authorization detail are required.
 *
 * @param issuerKeys issuing agent's keypair (for a root, this becomes the token's own keypair)
 * @param issuerOvid parent's OVID; null for a root token
 * @param authorizationDetails RFC 9396 details; the first entry receives the OVID chain extensions
 * @param issuer issuer ID; defaults to the parent's sub, or {@code "root"}
 * @param agentId unique agent ID; autogenerated as {@code <issuer>/agent-<hex>} when null
 * @param ttlSeconds time to live; defaults to 1800
 * @param kid optional key ID for the JWT header
 */
public record CreateOvidOptions(
    KeyPair issuerKeys,
    OvidToken issuerOvid,
    List<AuthorizationDetail> authorizationDetails,
    String issuer,
    String agentId,
    Long ttlSeconds,
    String kid) {

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder {
    private KeyPair issuerKeys;
    private OvidToken issuerOvid;
    private List<AuthorizationDetail> authorizationDetails;
    private String issuer;
    private String agentId;
    private Long ttlSeconds;
    private String kid;

    public Builder issuerKeys(KeyPair keys) {
      this.issuerKeys = keys;
      return this;
    }

    public Builder issuerOvid(OvidToken parent) {
      this.issuerOvid = parent;
      return this;
    }

    public Builder mandate(AuthorizationDetail detail) {
      this.authorizationDetails = List.of(detail);
      return this;
    }

    public Builder authorizationDetails(List<AuthorizationDetail> details) {
      this.authorizationDetails = List.copyOf(details);
      return this;
    }

    public Builder issuer(String issuer) {
      this.issuer = issuer;
      return this;
    }

    public Builder agentId(String agentId) {
      this.agentId = agentId;
      return this;
    }

    public Builder ttlSeconds(long ttlSeconds) {
      this.ttlSeconds = ttlSeconds;
      return this;
    }

    public Builder kid(String kid) {
      this.kid = kid;
      return this;
    }

    public CreateOvidOptions build() {
      return new CreateOvidOptions(
          issuerKeys, issuerOvid, authorizationDetails, issuer, agentId, ttlSeconds, kid);
    }
  }
}
